# server/app.py
import os
from openenv.core.env_server import create_fastapi_app, create_app
from models import AdPlatformAction, AdPlatformObservation
from server.environment import AdPlatformEnvironment
# env = CalcEnvironment()
# app = create_fastapi_app(env, CalcAction, CalcObservation)

# This dictionary lives as long as the server is running
# It maps Session IDs -> Environment Instances
_USER_ENVIRONMENTS = {}
def get_ad_platform_env(session_id: str = "default"):
    """
    OpenEnv calls this function. 
    If it's a new session, we create an env.
    If it's an existing session, we return the one we already have.
    """
    task_name = os.getenv("TASK", "budget")
    
    # This will print the actual UUID generated by OpenEnv in terminal
    print(f"DEBUG: Request received for Session ID: {session_id}")
    
    if session_id not in _USER_ENVIRONMENTS:
        # Create a brand new instance for this specific user
        print(f"DEBUG: Creating NEW instance for {session_id}")
        _USER_ENVIRONMENTS[session_id] = AdPlatformEnvironment(task=task_name)
    
    # Return the instance (state is preserved inside this object)
    return _USER_ENVIRONMENTS[session_id]

# Pass the factory function
app = create_app(
    get_ad_platform_env, 
    AdPlatformAction, 
    AdPlatformObservation,
    env_name="AdPlatform_env"
)
# app = create_fastapi_app(CalcEnvironment, CalcAction, CalcObservation)